spring:
  application:
    name: ${vcap.application.name:customer-service}

security:
  basic:
    enabled: false
management:
  security:
    enabled: false

info:
  build:
    artifact: @project.artifactId@
    name: @project.name@
    description: @project.description@
    version: @project.version@

logging:
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss.SSS} [ip=%X{ip}] [trace=%X{X-Trace-Id:-},span=%X{X-Span-Id:-}] [%15.15t] %-40.40logger{39}: %m%n'
  level:
    org.springframework.cloud.sleuth: DEBUG
